services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_SMTP_HOST: ${VITE_SMTP_HOST}
        VITE_SMTP_PORT: ${VITE_SMTP_PORT}
        VITE_SMTP_USER: ${VITE_SMTP_USER}
        VITE_SMTP_PASS: ${VITE_SMTP_PASS}
        VITE_MAIL_RECEIVER: ${VITE_MAIL_RECEIVER}
        VITE_SENDER_MAIL: ${VITE_SENDER_MAIL}
        LISTMONK_API_USER: ${LISTMONK_API_USER}
        LISTMONK_API_TOKEN: ${LISTMONK_API_TOKEN}
        LISTMONK_API_URL: ${LISTMONK_API_URL}
    image: wozniakslawomir/personal-website-frontend:latest
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_SMTP_HOST=${VITE_SMTP_HOST}
      - VITE_SMTP_PORT=${VITE_SMTP_PORT}
      - VITE_SMTP_USER=${VITE_SMTP_USER}
      - VITE_SMTP_PASS=${VITE_SMTP_PASS}
      - VITE_MAIL_RECEIVER=${VITE_MAIL_RECEIVER}
      - VITE_SENDER_MAIL=${VITE_SENDER_MAIL}
      - LISTMONK_API_USER=${LISTMONK_API_USER}
      - LISTMONK_API_TOKEN=${LISTMONK_API_TOKEN}
      - LISTMONK_API_URL=${LISTMONK_API_URL}
    ports:
      - 3000:3000
    volumes:
      - ./data:/.data

