services:
  frontend:
    build:
      context: .
    environment:
      - NUXT_PUBLIC_API_URL=${VITE_API_URL}
      - NUXT_VITE_SMTP_HOST=${VITE_SMTP_HOST}
      - NUXT_VITE_SMTP_PORT=${VITE_SMTP_PORT}
      - NUXT_VITE_SMTP_USER=${VITE_SMTP_USER}
      - NUXT_VITE_SMTP_PASS=${VITE_SMTP_PASS}
      - NUXT_VITE_MAIL_RECEIVER=${VITE_MAIL_RECEIVER}
      - NUXT_VITE_SENDER_MAIL=${VITE_SENDER_MAIL}
      - NUXT_LISTMONK_API_USER=${LISTMONK_API_USER}
      - NUXT_LISTMONK_API_TOKEN=${LISTMONK_API_TOKEN}
      - NUXT_LISTMONK_API_URL=${LISTMONK_API_URL}
    ports:
      - 3000:3000
    volumes:
      - ./data:/.data

